spring.application.name=su26sd09

# ===============================
# CẤU HÌNH KẾT NỐI SQL SERVER
# ===============================
# Đảm bảo SQL Server đang chạy ở port 1433
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quan_ly_khach_san;encrypt=true;trustServerCertificate=true
# Tài khoản đăng nhập SQL Server (thường mặc định là sa)
spring.datasource.username=sa
# ĐIỀN MẬT KHẨU SQL SERVER CỦA BẠN VÀO ĐÂY:
spring.datasource.password=123456
security.
# ===============================
# CẤU HÌNH HIBERNATE / JPA
# ===============================
# Hiển thị SQL trên console để dễ debug quá trình code
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Không để Spring Boot tự động sửa/xóa các bảng trong CSDL (vì bạn đã có file script SQL chuẩn rồi)
spring.jpa.hibernate.ddl-auto=none

# Cấu hình Dialect cho SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${CLIENT_USERNAME}
spring.mail.password=${CLIENT_PASSKEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=http://localhost:8080
