spring.application.name=su26sd09

# ===============================
# CẤU HÌNH ENCODING
# ===============================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# ===============================
# CẤU HÌNH KẾT NỐI SQL SERVER
# ===============================
# Dam bao SQL Server dang chay o port 1433
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quan_ly_khach_san;encrypt=true;trustServerCertificate=true
# Tài khoản Đăng nhập SQL Server (thuong mac dinh la sa)
spring.datasource.username=sa
# ĐIỀN MẬT KHẨU SQL SERVER CỦA BẠN VÀO ĐÂY:
spring.datasource.password=123456
# ===============================
# CẤU HÌNH HIBERNATE / JPA
# ===============================
# Hien thi SQL tren console de de debug qua trinh code
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Khong de Spring Boot tu dong sua/xoa cac bang trong CSDL (vi ban da co file script SQL chuan roi)
spring.jpa.hibernate.ddl-auto=none

# Cau hinh Dialect cho SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${CLIENT_USERNAME}
spring.mail.password=${CLIENT_PASSKEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=http://localhost:8080
